apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora
  namespace: nine
  labels:
    app.kubernetes.io/name: collabora
    app.kubernetes.io/part-of: ninekube
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: collabora
  template:
    metadata:
      labels:
        app.kubernetes.io/name: collabora
        app.kubernetes.io/part-of: ninekube
    spec:
      containers:
        - name: collabora
          image: collabora/code:latest
          ports:
            - containerPort: 9980
              name: http
          env:
            - name: domain
              value: "nextcloud.NINE_DOMAIN"
            - name: extra_params
              value: "--o:ssl.enable=false --o:ssl.termination=true"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
