apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustfs
  namespace: nine
  labels:
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/part-of: ninekube
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - rustfs.nine.local
      secretName: rustfs-tls
  rules:
    - host: rustfs.nine.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rustfs
                port:
                  number: 9001
