apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data
  namespace: nine
  labels:
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/part-of: ninekube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
