apiVersion: v1
kind: Service
metadata:
  name: rustfs
  namespace: nine
  labels:
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/part-of: ninekube
spec:
  selector:
    app.kubernetes.io/name: rustfs
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console
