apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: nine
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: ninekube
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: "changeme"
  AUTHENTIK_POSTGRESQL__PASSWORD: "changeme"
