apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

patches:
  - target:
      kind: Deployment
      name: authentik-server
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
  - target:
      kind: PersistentVolumeClaim
      name: minio-data
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 5Gi
  - target:
      kind: ConfigMap
      name: authentik-config
    patch: |
      - op: replace
        path: /data/AUTHENTIK_POSTGRESQL__HOST
        value: dev-postgres
      - op: replace
        path: /data/AUTHENTIK_REDIS__HOST
        value: dev-redis
