apiVersion: v1
kind: Secret
metadata:
  name: nine-secrets
  namespace: nine
  labels:
    app.kubernetes.io/part-of: ninekube
type: Opaque
stringData:
  LDAP_BIND_PASSWORD: "changeme"
  MINIO_ROOT_USER: "changeme"
  MINIO_ROOT_PASSWORD: "changeme"
