apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app.kubernetes.io/part-of: ninekube
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@nine.local
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
