apiVersion: v1
kind: ConfigMap
metadata:
  name: ninegate-glauth-config
  namespace: nine
  labels:
    app.kubernetes.io/name: glauth
    app.kubernetes.io/part-of: ninekube
    app.kubernetes.io/component: ninegate
data:
  config.cfg: |
    [backend]
      datastore = "plugin"
      plugin = "/app/postgres.so"
      pluginhandler = "NewPostgresHandler"
      database = "host=postgres port=5432 user=CHANGE_PG_USER password=CHANGE_PG_PASS dbname=ninegate sslmode=disable"
      baseDN = "dc=nine,dc=local"

    [ldap]
      enabled = true
      listen = "0.0.0.0:3893"
      tls = false

    [ldaps]
      enabled = false

    [behaviors]
      IgnoreCapabilities = true
      LimitFailedBinds = true
      NumberOfFailedBinds = 3
      PeriodOfFailedBinds = 10
      BlockFailedBindsFor = 60
      PruneSourceTableEvery = 600
      PruneSourcesOlderThan = 600
