apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ninegate-public-uploads
  namespace: nine
  labels:
    app.kubernetes.io/name: ninegate
    app.kubernetes.io/part-of: ninekube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
