apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: nine
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: ninekube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
