apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinyfilemanager-data
  namespace: nine
  labels:
    app.kubernetes.io/name: tinyfilemanager
    app.kubernetes.io/part-of: ninekube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
