apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nine
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/part-of: ninekube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
