apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: ninekube
rules:
  - apiGroups: [cert-manager.io]
    resources: [certificates, certificaterequests, issuers, clusterissuers]
    verbs: [get, list, watch, create, update, delete, patch]
  - apiGroups: [acme.cert-manager.io]
    resources: [orders, challenges]
    verbs: [get, list, watch, create, update, delete, patch]
  - apiGroups: [""]
    resources: [secrets, configmaps, services, events]
    verbs: [get, list, watch, create, update, delete, patch]
  - apiGroups: [extensions, networking.k8s.io]
    resources: [ingresses]
    verbs: [get, list, watch, create, update, delete, patch]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: [get, list, watch, create, update, delete, patch]
