apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nextcloud
  - tinyfilemanager
  - namespace.yaml
  - shared
  - minio
  - postgres
  - redis
  - authentik

configMapGenerator:
  - name: nine-config
    envs:
      - .env
    options:
      disableNameSuffixHash: true
