apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nine
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: ninekube
type: Opaque
stringData:
  username: authentik
  password: changeme
